version: "3"
services:
  db:
      image: pgvector/pgvector:pg16
      # persist data beyond lifetime of container
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      #- postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      healthcheck:
        test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
        interval: 2s
        retries: 10
      expose:
        - 5432
      ports:
        - "5432:5432"